### ISSUE TITLE
CrossCore Error while trying to blink leds

### ISSUE THREAD

**Issue by mayraamaral** [analogdevicesinc/EVAL-ADICUP3029#40]
Hello! 
I was trying to blink some LEDs (it is my first time with ADICUP and LoRa), I did installed every external pack that was needed as said in Analog's website but when I tried to send the code to the board, I can't, and it shows on the screen: 
![erro](https://user-images.githubusercontent.com/38574181/66509546-adeeed00-eaa9-11e9-8b93-a923ab3fdfec.PNG)

Btw I don't know if I'm doing right, can you help me with sending code to the board, please?

My board is ADICUP3029

Best regards,
Mayra Amaral.

**Comment by mirceacaprioru** [comment]
Hi Mayra,

You can check some of these links:
https://wiki.analog.com/resources/eval/user-guides/eval-adicup3029
https://wiki.analog.com/resources/eval/user-guides/eval-adicup3029/tools/cces_user_guide
https://wiki.analog.com/resources/eval/user-guides/eval-adicup3029/tools/adicup3029_hw_drivers

They are a good starting point and should get you up an running. 

Regards,
Mircea

**Comment by mayraamaral** [comment]
Thank you very much. I did read the user guide but it was from the ADICUP board, not from CrossCore Platform. I will do it.

Regards,
Mayra.
